import type { TraceForgeApiStore, CreateTaskDto, CreateApprovalDto, RunDto, ActivityDto } from "@traceforge/api";
import type { ArtifactStore, Clock, IdGenerator } from "@traceforge/application";
import type { Approval, Artifact, GitCommit, GitFileChange, RunGitAssociation, Task } from "@traceforge/domain";
import { PostgresEventRepository } from "./postgres-event-repository.js";
import type { Pool } from "pg";

interface TaskRow { task_id:string;title:string;repository:string;workspace:string;created_at:Date;created_by:string;status:Task["status"] }
interface RunRow { run_id:string;task_id:string;session_id:string;status:string;started_at:Date;completed_at:Date|null }
interface ArtifactRow { artifact_id:string;run_id:string;artifact_type:string;relative_path:string;mime_type:string;size_bytes:number;content_hash:string;hash_algorithm:"sha256";created_at:Date;created_by_agent:string;storage_reference:string }
interface CommitRow { repository:string;commit_id:string;branch:string|null;base_commit:string|null;author:string;author_email:string;committed_at:Date;changed_files:GitFileChange[] }
interface AssociationRow { run_id:string;repository:string;commit_id:string;evidence:RunGitAssociation["evidence"];matched_artifact_ids:string[];unmatched_artifact_ids:string[] }
interface ActivityRow {activity_id:string;event_id:string;run_id:string;sequence:string|number;activity_type:string;actor_name:string;provider:string|null;model:string|null;summary:string;occurred_at:Date}

export class PostgresTraceForgeApiStore implements TraceForgeApiStore {
  private readonly events: PostgresEventRepository;
  public constructor(private readonly pool:Pool, private readonly artifacts:ArtifactStore, private readonly clock:Clock, private readonly ids:IdGenerator){this.events=new PostgresEventRepository(pool)}
  public async createTask(input:CreateTaskDto&{readonly createdBy:string}):Promise<Task>{const task:Task={taskId:this.ids.generate(),...input,createdAt:this.clock.now().toISOString(),status:"OPEN"};await this.pool.query("INSERT INTO tasks (task_id,title,repository,workspace,created_at,created_by,status) VALUES ($1,$2,$3,$4,$5,$6,$7)",[task.taskId,task.title,task.repository,task.workspace,task.createdAt,task.createdBy,task.status]);return task}
  public async listTasks():Promise<readonly Task[]>{const r=await this.pool.query<TaskRow>("SELECT * FROM tasks ORDER BY created_at DESC, task_id DESC");return r.rows.map(task)}
  public async getTask(id:string):Promise<Task|null>{const row=(await this.pool.query<TaskRow>("SELECT * FROM tasks WHERE task_id=$1",[id])).rows[0];return row?task(row):null}
  public async getRun(id:string):Promise<RunDto|null>{const row=(await this.pool.query<RunRow>("SELECT r.run_id,s.task_id,r.session_id,r.status,r.started_at,r.completed_at FROM agent_runs r JOIN sessions s ON s.session_id=r.session_id WHERE r.run_id=$1",[id])).rows[0];return row?{runId:row.run_id,taskId:row.task_id,sessionId:row.session_id,status:row.status,startedAt:row.started_at.toISOString(),...(row.completed_at?{completedAt:row.completed_at.toISOString()}:{})}:null}
  public async getLatestRun():Promise<RunDto|null>{const row=(await this.pool.query<RunRow>("SELECT r.run_id,s.task_id,r.session_id,r.status,r.started_at,r.completed_at FROM agent_runs r JOIN sessions s ON s.session_id=r.session_id JOIN integration_run_contexts c ON c.run_id=r.run_id ORDER BY c.created_at DESC LIMIT 1")).rows[0];return row?{runId:row.run_id,taskId:row.task_id,sessionId:row.session_id,status:row.status,startedAt:row.started_at.toISOString(),...(row.completed_at?{completedAt:row.completed_at.toISOString()}:{})}:null}
  public async listLatestActivities(limit:number,runId?:string):Promise<readonly ActivityDto[]>{const result=await this.pool.query<ActivityRow>(`SELECT activity_id,event_id,run_id,sequence,activity_type,actor_name,provider,model,summary,occurred_at FROM opencode_activities ${runId?"WHERE run_id=$2":""} ORDER BY recorded_at DESC,activity_id DESC LIMIT $1`,runId?[limit,runId]:[limit]);return result.rows.map(row=>({activityId:row.activity_id,eventId:row.event_id,runId:row.run_id,sequence:Number(row.sequence),activityType:row.activity_type,actorName:row.actor_name,...(row.provider?{provider:row.provider}:{}),...(row.model?{model:row.model}:{}),summary:row.summary,occurredAt:row.occurred_at.toISOString()}));}
  public listRunEvents(id:string){return this.events.listRunEvents(id)}
  public async listRunArtifacts(id:string):Promise<readonly Artifact[]>{return (await this.pool.query<ArtifactRow>("SELECT * FROM artifacts WHERE run_id=$1 ORDER BY created_at,artifact_id",[id])).rows.map(artifact)}
  public async getArtifact(id:string):Promise<Artifact|null>{const row=(await this.pool.query<ArtifactRow>("SELECT * FROM artifacts WHERE artifact_id=$1",[id])).rows[0];return row?artifact(row):null}
  public getArtifactContent(hash:string){return this.artifacts.get(hash)}
  public async createApproval(input:CreateApprovalDto&{readonly reviewer:string}):Promise<Approval>{const value:Approval={approvalId:this.ids.generate(),runId:input.runId,target:input.artifactId?{artifactId:input.artifactId}:{manifestId:input.manifestId!},reviewer:input.reviewer,decision:input.decision,timestamp:this.clock.now().toISOString(),...(input.comment?{comment:input.comment}:{})};await this.pool.query("INSERT INTO approvals (approval_id,run_id,artifact_id,manifest_id,reviewer,decision,decided_at,comment) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[value.approvalId,value.runId,value.target.artifactId??null,value.target.manifestId??null,value.reviewer,value.decision,value.timestamp,value.comment??null]);return value}
  public async getCommit(id:string):Promise<{readonly commit:GitCommit;readonly associations:readonly RunGitAssociation[]}|null>{const rows=(await this.pool.query<CommitRow>("SELECT * FROM git_commits WHERE commit_id=$1 ORDER BY repository LIMIT 2",[id])).rows;if(rows.length>1)throw new Error("Commit ID is ambiguous across repositories");const row=rows[0];if(!row)return null;const associations=(await this.pool.query<AssociationRow>("SELECT * FROM run_git_commits WHERE repository=$1 AND commit_id=$2 ORDER BY associated_at,run_id",[row.repository,id])).rows.map(a=>({runId:a.run_id,repository:a.repository,commitId:a.commit_id,evidence:a.evidence,matchedArtifactIds:a.matched_artifact_ids,unmatchedArtifactIds:a.unmatched_artifact_ids}));return{commit:{repository:row.repository,commitId:row.commit_id,branch:row.branch,baseCommit:row.base_commit,author:row.author,authorEmail:row.author_email,timestamp:row.committed_at.toISOString(),changedFiles:row.changed_files},associations}}
}
function task(r:TaskRow):Task{return{taskId:r.task_id,title:r.title,repository:r.repository,workspace:r.workspace,createdAt:r.created_at.toISOString(),createdBy:r.created_by,status:r.status}}
function artifact(r:ArtifactRow):Artifact{return{artifactId:r.artifact_id,runId:r.run_id,artifactType:r.artifact_type,relativePath:r.relative_path,mimeType:r.mime_type,size:Number(r.size_bytes),contentHash:r.content_hash,hashAlgorithm:r.hash_algorithm,createdAt:r.created_at.toISOString(),createdByAgent:r.created_by_agent,storageReference:r.storage_reference}}
