export const PROVENANCE_EVENT_TYPES = [
  "PROJECT_CREATED",
  "TASK_CREATED",
  "TASK_UPDATED",
  "TASK_COMPLETED",
  "SESSION_STARTED",
  "SESSION_COMPLETED",
  "PROMPT_SUBMITTED",
  "AGENT_STARTED",
  "AGENT_COMPLETED",
  "AGENT_FAILED",
  "MODEL_REQUEST",
  "MODEL_RESPONSE",
  "MODEL_ERROR",
  "TOOL_STARTED",
  "TOOL_COMPLETED",
  "TOOL_FAILED",
  "RESOURCE_ACCESSED",
  "FILE_READ",
  "FILE_CREATED",
  "FILE_MODIFIED",
  "FILE_DELETED",
  "FILE_RENAMED",
  "CODE_DIFF_GENERATED",
  "TERMINAL_COMMAND_STARTED",
  "TERMINAL_COMMAND_COMPLETED",
  "TERMINAL_COMMAND_FAILED",
  "TEST_STARTED",
  "TEST_COMPLETED",
  "TEST_FAILED",
  "TEST_EXECUTION",
  "ARTIFACT_CREATED",
  "ARTIFACT_MODIFIED",
  "HUMAN_APPROVAL",
  "HUMAN_REJECTION",
  "CHANGES_REQUESTED",
  "GIT_COMMIT_CREATED",
  "RUN_FAILED",
  "INTEGRITY_VERIFIED",
  "INTEGRITY_FAILED",
  "ERROR",
  "RUN_COMPLETED"
] as const;

export type ProvenanceEventType = (typeof PROVENANCE_EVENT_TYPES)[number];
export type EvidenceLevel =
  | "OBSERVED"
  | "DECLARED"
  | "INFERRED"
  | "NOT_OBSERVED"
  | "UNKNOWN"
  | "NOT_AVAILABLE";
export type ActorType = "human" | "agent" | "model" | "tool" | "system";
