import type { ArtifactStore,Clock,IdGenerator,StoredArtifact } from "@traceforge/application";
import { describe,expect,it,vi } from "vitest";
import { PostgresTraceForgeApiStore } from "../src/index.js";
class FixedClock implements Clock{public now(){return new Date("2026-08-22T12:00:00.000Z")}}
class Ids implements IdGenerator{public generate(){return"generated-1"}}
class Artifacts implements ArtifactStore{public async put():Promise<StoredArtifact>{throw new Error("unused")}public async get(hash:string){return hash==="a".repeat(64)?new Uint8Array([1]):null}public async exists(){return false}}
describe("PostgresTraceForgeApiStore",()=>{
  it("creates tasks with server-owned IDs and times",async()=>{const query=vi.fn(async()=>({rows:[]}));const store=new PostgresTraceForgeApiStore({query} as never,new Artifacts(),new FixedClock(),new Ids());const task=await store.createTask({title:"Build",repository:"repo",workspace:"ws",createdBy:"user@example.test"});expect(task).toMatchObject({taskId:"generated-1",createdAt:"2026-08-22T12:00:00.000Z",status:"OPEN"});expect(query).toHaveBeenCalledWith(expect.stringContaining("INSERT INTO tasks"),expect.arrayContaining(["generated-1","Build","repo","ws","2026-08-22T12:00:00.000Z","user@example.test","OPEN"]))});
  it("maps persistence rows to allowlisted domain objects and content storage",async()=>{const query=vi.fn(async(sql:string)=>sql.includes("FROM artifacts")?{rows:[{artifact_id:"a1",run_id:"r1",artifact_type:"source",relative_path:"src/a.ts",mime_type:"text/typescript",size_bytes:"4",content_hash:"a".repeat(64),hash_algorithm:"sha256",created_at:new Date("2026-08-22T12:00:00Z"),created_by_agent:"agent",storage_reference:"secret-ref"}]}:{rows:[]});const store=new PostgresTraceForgeApiStore({query} as never,new Artifacts(),new FixedClock(),new Ids());expect(await store.getArtifact("a1")).toMatchObject({artifactId:"a1",size:4,storageReference:"secret-ref"});expect(await store.getArtifactContent("a".repeat(64))).toEqual(new Uint8Array([1]))});
  it("rejects ambiguous commit IDs across repositories",async()=>{const query=vi.fn(async()=>({rows:[{repository:"a"},{repository:"b"}]}));const store=new PostgresTraceForgeApiStore({query} as never,new Artifacts(),new FixedClock(),new Ids());await expect(store.getCommit("same")).rejects.toThrow("ambiguous")});
});
